import React from 'react';
import { CalculatorIcon, CurrencyRupeeIcon, ClockIcon } from '@heroicons/react/24/outline';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const CapacityCard = ({ selectedPincode }) => {
  if (!selectedPincode) {
    return (
      <div className="bg-white border border-uidai-border rounded-lg p-6 h-full flex items-center justify-center text-gray-400 text-sm">
        Select a pincode to view capacity plan
      </div>
    );
  }

  const handleGeneratePDF = async () => {
    // Create a temporary element for the PDF content
    const pdfContent = document.createElement('div');
    pdfContent.style.padding = '20px';
    pdfContent.style.fontFamily = 'Inter, sans-serif';
    pdfContent.style.width = '600px';
    pdfContent.innerHTML = `
      <div style="border: 1px solid #E5E7EB; padding: 20px;">
        <h1 style="color: #0066CC; font-size: 18px; margin-bottom: 20px; border-bottom: 2px solid #0066CC; padding-bottom: 10px;">
          Q2 2026 CAPACITY PLAN - ${selectedPincode.state.toUpperCase()}
        </h1>
        <div style="margin-bottom: 20px;">
          <h2 style="font-size: 14px; color: #374151; margin-bottom: 5px;">Selected Pincode: ${selectedPincode.pincode}</h2>
          <p style="font-size: 12px; color: #6B7280;">District: ${selectedPincode.district}</p>
        </div>
        
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          <thead>
            <tr style="background-color: #0066CC; color: white;">
              <th style="padding: 8px; text-align: left; font-size: 12px;">Metric</th>
              <th style="padding: 8px; text-align: left; font-size: 12px;">Value</th>
            </tr>
          </thead>
          <tbody>
            <tr style="border-bottom: 1px solid #E5E7EB;">
              <td style="padding: 8px; font-size: 12px;">Forecast Demand</td>
              <td style="padding: 8px; font-size: 12px;">${selectedPincode.forecast_monthly}/mo (+${selectedPincode.surge_pct}%)</td>
            </tr>
            <tr style="border-bottom: 1px solid #E5E7EB;">
              <td style="padding: 8px; font-size: 12px;">Rec. Machines</td>
              <td style="padding: 8px; font-size: 12px;">${selectedPincode.recommended_machines}</td>
            </tr>
            <tr style="border-bottom: 1px solid #E5E7EB;">
              <td style="padding: 8px; font-size: 12px;">Est. Budget</td>
              <td style="padding: 8px; font-size: 12px;">₹${selectedPincode.budget_lakhs} Lakhs</td>
            </tr>
          </tbody>
        </table>

        <div style="background-color: #F3F4F6; padding: 10px; border-radius: 4px;">
           <p style="font-size: 10px; color: #6B7280;">Generated by Aadhaar Early Warning System</p>
        </div>
      </div>
    `;

    document.body.appendChild(pdfContent);

    try {
      const canvas = await html2canvas(pdfContent);
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`capacity_plan_${selectedPincode.pincode}.pdf`);
    } finally {
      document.body.removeChild(pdfContent);
    }
  };

  return (
    <div className="bg-white border border-uidai-border rounded-lg p-6 h-full flex flex-col">
      <h3 className="text-lg font-bold text-uidai-text mb-4">CAPACITY RECOMMENDATIONS</h3>

      <div className="mb-6">
        <div className="flex justify-between text-sm mb-1">
          <span className="text-gray-500">Pincode:</span>
          <span className="font-medium text-gray-900">{selectedPincode.pincode}</span>
        </div>
        <div className="flex justify-between text-sm mb-1">
          <span className="text-gray-500">Forecast:</span>
          <span className="font-medium text-gray-900">
            {selectedPincode.forecast_monthly}/mo
            <span className="text-red-600 ml-1">(+{selectedPincode.surge_pct}%)</span>
          </span>
        </div>
      </div>

      <div className="space-y-4 mb-6">
        <div className="bg-red-50 p-3 rounded border border-red-100">
          <p className="text-xs text-red-700 font-semibold uppercase mb-1">Current State</p>
          <div className="flex justify-between items-center">
            <span className="text-sm text-gray-700">{selectedPincode.current_machines} Machine</span>
            <span className="text-sm font-bold text-red-700">{selectedPincode.wait_time_hours}hr Wait</span>
          </div>
        </div>

        <div className="bg-green-50 p-3 rounded border border-green-100">
          <p className="text-xs text-green-700 font-semibold uppercase mb-1">Recommended</p>
          <div className="flex justify-between items-center">
            <span className="text-sm text-gray-700">{selectedPincode.recommended_machines} Machines</span>
            <span className="text-sm font-bold text-green-700">{selectedPincode.projected_wait_time_min}min Wait</span>
          </div>
        </div>
      </div>

      <div className="mb-6">
        <p className="text-xs font-semibold text-gray-700 mb-2 flex items-center">
          <CalculatorIcon className="w-3 h-3 mr-1" /> OPERATIONS MATH
        </p>
        <div className="grid grid-cols-3 gap-2 text-center">
          <div className="bg-gray-50 p-2 rounded">
            <p className="text-[10px] text-gray-500">Arrival (λ)</p>
            <p className="text-xs font-medium">{selectedPincode.lambda}/hr</p>
          </div>
          <div className="bg-gray-50 p-2 rounded">
            <p className="text-[10px] text-gray-500">Service (μ)</p>
            <p className="text-xs font-medium">{selectedPincode.mu}/hr</p>
          </div>
          <div className="bg-gray-50 p-2 rounded">
            <p className="text-[10px] text-gray-500">Wait</p>
            <p className="text-xs font-medium">~12min</p>
          </div>
        </div>
      </div>

      <div className="mt-auto">
        <div className="flex items-center justify-between mb-4 text-sm">
          <span className="text-gray-500 flex items-center"><CurrencyRupeeIcon className="w-4 h-4 mr-1" />Est. Budget</span>
          <span className="font-bold text-gray-900">₹{selectedPincode.budget_lakhs} Lakhs</span>
        </div>
        <button
          onClick={handleGeneratePDF}
          className="w-full border border-uidai-blue text-uidai-blue font-medium py-2 px-4 rounded-md hover:bg-blue-50 transition-colors text-sm"
        >
          Generate Q2 Capacity Plan PDF
        </button>
      </div>
    </div>
  );
};

export default CapacityCard;
